import "the-new-css-reset/css/reset.css";
import "@/style/tailwind.css";
// import { QueryClientProvider } from "@tanstack/react-query";
import type { ReactNode } from "react";

// import { rocketApiClient } from "@/utils/rocketApiClient";

export const metadata = {
  title: "UMT",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        {/* <QueryClientProvider client={rocketApiClient}> */}
        {children}
        {/* </QueryClientProvider> */}
      </body>
    </html>
  );
}
