import "the-new-css-reset/css/reset.css";
import "@/style/tailwind.css";
import type { ReactNode } from "react";

export const metadata = {
  title: "UMT",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: ReactNode;
}) {
  return (
    <html lang="ja">
      <body>{children}</body>
    </html>
  );
}
